source-file ~/.config/tmux/tmux.conf

# Flow session (thinking)
new-session -s flow -n 1-list -d
send-keys -t flow 'cd ~/flow/' C-m
send-keys -t flow 'nvim capture.md' C-m

new-window -n 2-rank -t flow
send-keys -t flow:2 'cd ~/flow/' C-m
send-keys -t flow:2 'nvim priority.md' C-m
split-window -h -t flow:2
send-keys -t flow:2.2 'cd ~/flow/ && watch -n 1 glow priority.md' C-m

new-window -n 3-iterate -t flow
send-keys -t flow:3 'cd ~/flow/' C-m
send-keys -t flow:3 'nvim now.md' C-m
split-window -h -t flow:3
send-keys -t flow:3.2 'cd ~/flow/' C-m

# Dev session (building)
new-session -s dev -n code -d
send-keys -t dev 'cd ~/dev/vox/' C-m
new-window -n terminal -t dev
send-keys -t dev:2 'cd ~/dev/vox/' C-m
new-window -n git -t dev
send-keys -t dev:3 'cd ~/dev/vox' C-m

# Start in flow
select-window -t flow:1
